spring:
  application:
    name: cloud-grpc-client
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://172.17.15.54:9411
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.17.15.52:8762/eureka/,http://172.17.15.53:8763/eureka/

grpc:
  client:
    cloud-grpc-server:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
